/* File: cwignerdmodule.c
 * This file is auto-generated with f2py (version:1.23.5).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Apr 22 23:47:17 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *cwignerd_error;
static PyObject *cwignerd_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = cwignerd_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void wignerd_cl_from_cf(int,int,int,int,int,double*,double*,double*,double*);
extern void wignerd_cf_from_cl(int,int,int,int,int,double*,double*,double*);
extern void init_gauss_legendre_quadrature(int,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/***************************** wignerd_cl_from_cf *****************************/
static char doc_f2py_rout_cwignerd_wignerd_cl_from_cf[] = "\
out_cl = wignerd_cl_from_cf(s1,s2,nfunc,ntheta,lmax,cos_theta,integration_weights,in_cf)\n\nWrapper for ``wignerd_cl_from_cf``.\
\n\nParameters\n----------\n"
"s1 : input int\n"
"s2 : input int\n"
"nfunc : input int\n"
"ntheta : input int\n"
"lmax : input int\n"
"cos_theta : input rank-1 array('d') with bounds (ntheta)\n"
"integration_weights : input rank-1 array('d') with bounds (ntheta)\n"
"in_cf : input rank-1 array('d') with bounds (nfunc * ntheta)\n"
"\nReturns\n-------\n"
"out_cl : rank-1 array('d') with bounds (nfunc + lmax * nfunc)";
/* extern void wignerd_cl_from_cf(int,int,int,int,int,double*,double*,double*,double*); */
static PyObject *f2py_rout_cwignerd_wignerd_cl_from_cf(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int,int,int,int,int,double*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int s1 = 0;
    PyObject *s1_capi = Py_None;
    int s2 = 0;
    PyObject *s2_capi = Py_None;
    int nfunc = 0;
    PyObject *nfunc_capi = Py_None;
    int ntheta = 0;
    PyObject *ntheta_capi = Py_None;
    int lmax = 0;
    PyObject *lmax_capi = Py_None;
    double *cos_theta = NULL;
    npy_intp cos_theta_Dims[1] = {-1};
    const int cos_theta_Rank = 1;
    PyArrayObject *capi_cos_theta_tmp = NULL;
    int capi_cos_theta_intent = 0;
    PyObject *cos_theta_capi = Py_None;
    double *integration_weights = NULL;
    npy_intp integration_weights_Dims[1] = {-1};
    const int integration_weights_Rank = 1;
    PyArrayObject *capi_integration_weights_tmp = NULL;
    int capi_integration_weights_intent = 0;
    PyObject *integration_weights_capi = Py_None;
    double *out_cl = NULL;
    npy_intp out_cl_Dims[1] = {-1};
    const int out_cl_Rank = 1;
    PyArrayObject *capi_out_cl_tmp = NULL;
    int capi_out_cl_intent = 0;
    double *in_cf = NULL;
    npy_intp in_cf_Dims[1] = {-1};
    const int in_cf_Rank = 1;
    PyArrayObject *capi_in_cf_tmp = NULL;
    int capi_in_cf_intent = 0;
    PyObject *in_cf_capi = Py_None;
    static char *capi_kwlist[] = {"s1","s2","nfunc","ntheta","lmax","cos_theta","integration_weights","in_cf",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOO|:cwignerd.wignerd_cl_from_cf",\
        capi_kwlist,&s1_capi,&s2_capi,&nfunc_capi,&ntheta_capi,&lmax_capi,&cos_theta_capi,&integration_weights_capi,&in_cf_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable s1 */
        f2py_success = int_from_pyobj(&s1,s1_capi,"cwignerd.wignerd_cl_from_cf() 1st argument (s1) can't be converted to int");
    if (f2py_success) {
    /* Processing variable s2 */
        f2py_success = int_from_pyobj(&s2,s2_capi,"cwignerd.wignerd_cl_from_cf() 2nd argument (s2) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nfunc */
        f2py_success = int_from_pyobj(&nfunc,nfunc_capi,"cwignerd.wignerd_cl_from_cf() 3rd argument (nfunc) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ntheta */
        f2py_success = int_from_pyobj(&ntheta,ntheta_capi,"cwignerd.wignerd_cl_from_cf() 4th argument (ntheta) can't be converted to int");
    if (f2py_success) {
    /* Processing variable lmax */
        f2py_success = int_from_pyobj(&lmax,lmax_capi,"cwignerd.wignerd_cl_from_cf() 5th argument (lmax) can't be converted to int");
    if (f2py_success) {
    /* Processing variable cos_theta */
    cos_theta_Dims[0]=ntheta;
    capi_cos_theta_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
    capi_cos_theta_tmp = array_from_pyobj(NPY_DOUBLE,cos_theta_Dims,cos_theta_Rank,capi_cos_theta_intent,cos_theta_capi);
    if (capi_cos_theta_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : cwignerd_error,"failed in converting 6th argument `cos_theta' of cwignerd.wignerd_cl_from_cf to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        cos_theta = (double *)(PyArray_DATA(capi_cos_theta_tmp));

    /* Processing variable integration_weights */
    integration_weights_Dims[0]=ntheta;
    capi_integration_weights_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
    capi_integration_weights_tmp = array_from_pyobj(NPY_DOUBLE,integration_weights_Dims,integration_weights_Rank,capi_integration_weights_intent,integration_weights_capi);
    if (capi_integration_weights_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : cwignerd_error,"failed in converting 7th argument `integration_weights' of cwignerd.wignerd_cl_from_cf to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        integration_weights = (double *)(PyArray_DATA(capi_integration_weights_tmp));

    /* Processing variable out_cl */
    out_cl_Dims[0]=nfunc + lmax * nfunc;
    capi_out_cl_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE|F2PY_INTENT_C;
    capi_out_cl_tmp = array_from_pyobj(NPY_DOUBLE,out_cl_Dims,out_cl_Rank,capi_out_cl_intent,Py_None);
    if (capi_out_cl_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : cwignerd_error,"failed in converting hidden `out_cl' of cwignerd.wignerd_cl_from_cf to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        out_cl = (double *)(PyArray_DATA(capi_out_cl_tmp));

    /* Processing variable in_cf */
    in_cf_Dims[0]=nfunc * ntheta;
    capi_in_cf_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
    capi_in_cf_tmp = array_from_pyobj(NPY_DOUBLE,in_cf_Dims,in_cf_Rank,capi_in_cf_intent,in_cf_capi);
    if (capi_in_cf_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : cwignerd_error,"failed in converting 8th argument `in_cf' of cwignerd.wignerd_cl_from_cf to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        in_cf = (double *)(PyArray_DATA(capi_in_cf_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(s1,s2,nfunc,ntheta,lmax,cos_theta,integration_weights,out_cl,in_cf);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_out_cl_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_in_cf_tmp!=in_cf_capi) {
        Py_XDECREF(capi_in_cf_tmp); }
    }  /*if (capi_in_cf_tmp == NULL) ... else of in_cf*/
    /* End of cleaning variable in_cf */
    }  /*if (capi_out_cl_tmp == NULL) ... else of out_cl*/
    /* End of cleaning variable out_cl */
    if((PyObject *)capi_integration_weights_tmp!=integration_weights_capi) {
        Py_XDECREF(capi_integration_weights_tmp); }
    }  /*if (capi_integration_weights_tmp == NULL) ... else of integration_weights*/
    /* End of cleaning variable integration_weights */
    if((PyObject *)capi_cos_theta_tmp!=cos_theta_capi) {
        Py_XDECREF(capi_cos_theta_tmp); }
    }  /*if (capi_cos_theta_tmp == NULL) ... else of cos_theta*/
    /* End of cleaning variable cos_theta */
    } /*if (f2py_success) of lmax*/
    /* End of cleaning variable lmax */
    } /*if (f2py_success) of ntheta*/
    /* End of cleaning variable ntheta */
    } /*if (f2py_success) of nfunc*/
    /* End of cleaning variable nfunc */
    } /*if (f2py_success) of s2*/
    /* End of cleaning variable s2 */
    } /*if (f2py_success) of s1*/
    /* End of cleaning variable s1 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************* end of wignerd_cl_from_cf *************************/

/***************************** wignerd_cf_from_cl *****************************/
static char doc_f2py_rout_cwignerd_wignerd_cf_from_cl[] = "\
out_cf = wignerd_cf_from_cl(s1,s2,nfunc,ntheta,lmax,cos_theta,in_cl)\n\nWrapper for ``wignerd_cf_from_cl``.\
\n\nParameters\n----------\n"
"s1 : input int\n"
"s2 : input int\n"
"nfunc : input int\n"
"ntheta : input int\n"
"lmax : input int\n"
"cos_theta : input rank-1 array('d') with bounds (ntheta)\n"
"in_cl : input rank-1 array('d') with bounds (nfunc + lmax * nfunc)\n"
"\nReturns\n-------\n"
"out_cf : rank-1 array('d') with bounds (nfunc * ntheta)";
/* extern void wignerd_cf_from_cl(int,int,int,int,int,double*,double*,double*); */
static PyObject *f2py_rout_cwignerd_wignerd_cf_from_cl(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int,int,int,int,int,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int s1 = 0;
    PyObject *s1_capi = Py_None;
    int s2 = 0;
    PyObject *s2_capi = Py_None;
    int nfunc = 0;
    PyObject *nfunc_capi = Py_None;
    int ntheta = 0;
    PyObject *ntheta_capi = Py_None;
    int lmax = 0;
    PyObject *lmax_capi = Py_None;
    double *cos_theta = NULL;
    npy_intp cos_theta_Dims[1] = {-1};
    const int cos_theta_Rank = 1;
    PyArrayObject *capi_cos_theta_tmp = NULL;
    int capi_cos_theta_intent = 0;
    PyObject *cos_theta_capi = Py_None;
    double *out_cf = NULL;
    npy_intp out_cf_Dims[1] = {-1};
    const int out_cf_Rank = 1;
    PyArrayObject *capi_out_cf_tmp = NULL;
    int capi_out_cf_intent = 0;
    double *in_cl = NULL;
    npy_intp in_cl_Dims[1] = {-1};
    const int in_cl_Rank = 1;
    PyArrayObject *capi_in_cl_tmp = NULL;
    int capi_in_cl_intent = 0;
    PyObject *in_cl_capi = Py_None;
    static char *capi_kwlist[] = {"s1","s2","nfunc","ntheta","lmax","cos_theta","in_cl",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOO|:cwignerd.wignerd_cf_from_cl",\
        capi_kwlist,&s1_capi,&s2_capi,&nfunc_capi,&ntheta_capi,&lmax_capi,&cos_theta_capi,&in_cl_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable s1 */
        f2py_success = int_from_pyobj(&s1,s1_capi,"cwignerd.wignerd_cf_from_cl() 1st argument (s1) can't be converted to int");
    if (f2py_success) {
    /* Processing variable s2 */
        f2py_success = int_from_pyobj(&s2,s2_capi,"cwignerd.wignerd_cf_from_cl() 2nd argument (s2) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nfunc */
        f2py_success = int_from_pyobj(&nfunc,nfunc_capi,"cwignerd.wignerd_cf_from_cl() 3rd argument (nfunc) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ntheta */
        f2py_success = int_from_pyobj(&ntheta,ntheta_capi,"cwignerd.wignerd_cf_from_cl() 4th argument (ntheta) can't be converted to int");
    if (f2py_success) {
    /* Processing variable lmax */
        f2py_success = int_from_pyobj(&lmax,lmax_capi,"cwignerd.wignerd_cf_from_cl() 5th argument (lmax) can't be converted to int");
    if (f2py_success) {
    /* Processing variable cos_theta */
    cos_theta_Dims[0]=ntheta;
    capi_cos_theta_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
    capi_cos_theta_tmp = array_from_pyobj(NPY_DOUBLE,cos_theta_Dims,cos_theta_Rank,capi_cos_theta_intent,cos_theta_capi);
    if (capi_cos_theta_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : cwignerd_error,"failed in converting 6th argument `cos_theta' of cwignerd.wignerd_cf_from_cl to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        cos_theta = (double *)(PyArray_DATA(capi_cos_theta_tmp));

    /* Processing variable out_cf */
    out_cf_Dims[0]=nfunc * ntheta;
    capi_out_cf_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE|F2PY_INTENT_C;
    capi_out_cf_tmp = array_from_pyobj(NPY_DOUBLE,out_cf_Dims,out_cf_Rank,capi_out_cf_intent,Py_None);
    if (capi_out_cf_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : cwignerd_error,"failed in converting hidden `out_cf' of cwignerd.wignerd_cf_from_cl to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        out_cf = (double *)(PyArray_DATA(capi_out_cf_tmp));

    /* Processing variable in_cl */
    in_cl_Dims[0]=nfunc + lmax * nfunc;
    capi_in_cl_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
    capi_in_cl_tmp = array_from_pyobj(NPY_DOUBLE,in_cl_Dims,in_cl_Rank,capi_in_cl_intent,in_cl_capi);
    if (capi_in_cl_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : cwignerd_error,"failed in converting 7th argument `in_cl' of cwignerd.wignerd_cf_from_cl to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        in_cl = (double *)(PyArray_DATA(capi_in_cl_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(s1,s2,nfunc,ntheta,lmax,cos_theta,out_cf,in_cl);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_out_cf_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_in_cl_tmp!=in_cl_capi) {
        Py_XDECREF(capi_in_cl_tmp); }
    }  /*if (capi_in_cl_tmp == NULL) ... else of in_cl*/
    /* End of cleaning variable in_cl */
    }  /*if (capi_out_cf_tmp == NULL) ... else of out_cf*/
    /* End of cleaning variable out_cf */
    if((PyObject *)capi_cos_theta_tmp!=cos_theta_capi) {
        Py_XDECREF(capi_cos_theta_tmp); }
    }  /*if (capi_cos_theta_tmp == NULL) ... else of cos_theta*/
    /* End of cleaning variable cos_theta */
    } /*if (f2py_success) of lmax*/
    /* End of cleaning variable lmax */
    } /*if (f2py_success) of ntheta*/
    /* End of cleaning variable ntheta */
    } /*if (f2py_success) of nfunc*/
    /* End of cleaning variable nfunc */
    } /*if (f2py_success) of s2*/
    /* End of cleaning variable s2 */
    } /*if (f2py_success) of s1*/
    /* End of cleaning variable s1 */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************* end of wignerd_cf_from_cl *************************/

/*********************** init_gauss_legendre_quadrature ***********************/
static char doc_f2py_rout_cwignerd_init_gauss_legendre_quadrature[] = "\
x,w = init_gauss_legendre_quadrature(n)\n\nWrapper for ``init_gauss_legendre_quadrature``.\
\n\nParameters\n----------\n"
"n : input int\n"
"\nReturns\n-------\n"
"x : rank-1 array('d') with bounds (n)\n"
"w : rank-1 array('d') with bounds (n)";
/* extern void init_gauss_legendre_quadrature(int,double*,double*); */
static PyObject *f2py_rout_cwignerd_init_gauss_legendre_quadrature(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int n = 0;
    PyObject *n_capi = Py_None;
    double *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_tmp = NULL;
    int capi_x_intent = 0;
    double *w = NULL;
    npy_intp w_Dims[1] = {-1};
    const int w_Rank = 1;
    PyArrayObject *capi_w_tmp = NULL;
    int capi_w_intent = 0;
    static char *capi_kwlist[] = {"n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:cwignerd.init_gauss_legendre_quadrature",\
        capi_kwlist,&n_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable n */
        f2py_success = int_from_pyobj(&n,n_capi,"cwignerd.init_gauss_legendre_quadrature() 1st argument (n) can't be converted to int");
    if (f2py_success) {
    /* Processing variable x */
    x_Dims[0]=n;
    capi_x_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE|F2PY_INTENT_C;
    capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,Py_None);
    if (capi_x_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : cwignerd_error,"failed in converting hidden `x' of cwignerd.init_gauss_legendre_quadrature to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        x = (double *)(PyArray_DATA(capi_x_tmp));

    /* Processing variable w */
    w_Dims[0]=n;
    capi_w_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE|F2PY_INTENT_C;
    capi_w_tmp = array_from_pyobj(NPY_DOUBLE,w_Dims,w_Rank,capi_w_intent,Py_None);
    if (capi_w_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : cwignerd_error,"failed in converting hidden `w' of cwignerd.init_gauss_legendre_quadrature to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        w = (double *)(PyArray_DATA(capi_w_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(n,x,w);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NN",capi_x_tmp,capi_w_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /*if (capi_w_tmp == NULL) ... else of w*/
    /* End of cleaning variable w */
    }  /*if (capi_x_tmp == NULL) ... else of x*/
    /* End of cleaning variable x */
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************* end of init_gauss_legendre_quadrature *******************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"wignerd_cl_from_cf",-1,{{-1}},0,(char *)wignerd_cl_from_cf,(f2py_init_func)f2py_rout_cwignerd_wignerd_cl_from_cf,doc_f2py_rout_cwignerd_wignerd_cl_from_cf},
    {"wignerd_cf_from_cl",-1,{{-1}},0,(char *)wignerd_cf_from_cl,(f2py_init_func)f2py_rout_cwignerd_wignerd_cf_from_cl,doc_f2py_rout_cwignerd_wignerd_cf_from_cl},
    {"init_gauss_legendre_quadrature",-1,{{-1}},0,(char *)init_gauss_legendre_quadrature,(f2py_init_func)f2py_rout_cwignerd_init_gauss_legendre_quadrature,doc_f2py_rout_cwignerd_init_gauss_legendre_quadrature},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "cwignerd",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_cwignerd(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = cwignerd_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module cwignerd (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.23.5");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'cwignerd' is auto-generated with f2py (version:1.23.5).\nFunctions:\n"
"    out_cl = wignerd_cl_from_cf(s1,s2,nfunc,ntheta,lmax,cos_theta,integration_weights,in_cf)\n"
"    out_cf = wignerd_cf_from_cl(s1,s2,nfunc,ntheta,lmax,cos_theta,in_cl)\n"
"    x,w = init_gauss_legendre_quadrature(n)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.23.5");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    cwignerd_error = PyErr_NewException ("cwignerd.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_cwignerd_error", cwignerd_error);
    Py_DECREF(cwignerd_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }



/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"cwignerd");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
