base:
    dir_healqest:
    runname     : '092023'

cls:
    file_ucmb: '/lcrc/project/SPT3G/users/ac.yomori/repo/healqest/pipeline/camb/planck2018_base_plikHM_TTTEEE_lowl_lowE_lensing_lenspotentialCls.dat'
    file_lcmb: '/lcrc/project/SPT3G/users/ac.yomori/repo/healqest/pipeline/camb/planck2018_base_plikHM_TTTEEE_lowl_lowE_lensing_lensedCls.dat'
    file_gcmb: '/lcrc/project/SPT3G/users/ac.yomori/repo/healqest/pipeline/camb/planck2018_base_plikHM_TTTEEE_lowl_lowE_lensing_lensedCls_gradlensedCls.dat'
    
rec:
    rectype: 'sqe' # [sqe,gmv,mh,xilc,gmvph]
    cltype : 'lcmb'
    Lmax : 4100
    lmint: 320
    lmaxt: 4000
    lminp: 320
    lmaxp: 4000
    nside: 2048

inputs:
    alms: '/lcrc/project/SPT3G/users/ac.yomori/sims/spt3g_lensing_20192020/3.3.1.3.1/mockdata/healpix/cinv_{maptype}_N1/ivf_teb_cmbset{cmbset}_seed{seed}.alm'
    phi_in   : '/lcrc/project/SPT3G/users/ac.yomori/sims/planck2018_cmb_v2/unl/planck2018_base_plikHM_TTTEEE_lowl_lowE_lensing_cambphiG_phi1_seed{seed}.alm'
    kappa_in : '/lcrc/project/SPT3G/users/ac.yomori/sims/spt3g_lensing_20192020/inputkappa/inkappa_seed{seed}.alm'

outputs:
    dir_out : '/lcrc/project/SPT3G/users/ac.yomori/projects/spt3g_lensing_20192020/lensrec/{runname}/{rectype}_N1/lmaxt4000/'

pspec:
    dir_tmp  : '/tmp/'
    dir_cls  : '/lcrc/project/SPT3G/users/ac.yomori/projects/spt3g_lensing_20192020/lensrec/{runname}/{rectype}_N1/lmaxt4000/clkk/'
    file_mask: '/lcrc/project/SPT3G/users/ac.yomori/projects/spt3g_lensing_20192020/masks/mask2048_border_apod_mask_threshold0.1_allghz_dense_1500d_eetelensing-1920_mapmaking_mask_list_fluxcut6mJy_clusterSNcut10.fits'
    lmax     : 4100
    thetamax : 25
    apodizesigma: 30
    tolerance: 1e-8 
